version: '3'

services:
  git-server:
    image: quay.io/swo0k/git-http-backend:v0.0.1
    ports: ["9080:8080"]
    volumes:
    - /repositories/:/repositories/

  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=concourse_pass
    - POSTGRES_USER=concourse_user
    - PGDATA=/database

  concourse:
    image: concourse/concourse:5.0.0
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=http://docker:8080
    - CONCOURSE_ADD_LOCAL_USER=admin:admin
    - CONCOURSE_MAIN_TEAM_LOCAL_USER=admin
